project:
  type: website
  output-dir: docs

website:
  title: "Elian Giordano"
  navbar:
    left:
      - text: "About"        # <--- Explicitly naming the button "About"
        href: about.qmd
      - text: "CV"           # <--- Good practice to do this for CV too
        href: CV.qmd
      - courses.qmd
      - projects.qmd
      - code.qmd
    right:
      - icon: github
        href: https://github.com/eliangio
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/elian-giordano
        target: _blank

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true